/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-07-10 07:41:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.RentCarDAO;
import db.CarViewBean;
import java.util.Vector;

public final class CarReserveView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("db.CarViewBean");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("db.RentCarDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
 
	
		String id  =(String)session.getAttribute("id");
		
		if(id ==null){		
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\talert(\"로그인을 먼저 해주세요\");\r\n");
      out.write("\t\tlocation.href = 'RentcarMain.jsp?center=MemberLogin.jsp';\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
 
		}
		//로그인 되어있는 아이디를 읽어옴
		RentCarDAO rdao = new RentCarDAO();
		Vector<CarViewBean> v = rdao.getAllReserve(id);
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<table width=\"1000\">\r\n");
      out.write("\t\t\t<tr height=\"100\">\r\n");
      out.write("\t\t\t\t<td align=\"center\" colspan=\"11\">\r\n");
      out.write("\t\t\t\t\t<font size=\"6\" color=\"gray\">차량 예약 완료 화면</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table width=\"1000\" border=\"1\">\r\n");
      out.write("\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\">이미지 </td>\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\">이름 </td>\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\">대여일</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">대여기간</td>\r\n");
      out.write("\t\t\t\t<td width=\"100\"align=\"center\">금액</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">수량</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">보험</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">wifi유무</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">네비게이션</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">베이비시트유무</td>\r\n");
      out.write("\t\t\t\t<td width=\"90\"align=\"center\">삭제</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t");
 
			for(int i =0 ; i< v.size() ; i++){			
				CarViewBean bean = v.get(i);
	
      out.write("\r\n");
      out.write("\t\t\t<tr height=\"60\">\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\"><img alt =\"\" src=\"images/");
      out.print(bean.getImg());
      out.write("\"  width=\"120\" height=\"70\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\">");
      out.print(bean.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"150\"align=\"center\">");
      out.print(bean.getDday());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getRday());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"100\"align=\"center\">");
      out.print(bean.getPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getQty());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getUserin());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getUsewifi());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getUsenavi());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"60\"align=\"center\">");
      out.print(bean.getUseseat());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td width=\"90\"align=\"center\"><button onclick=\"location.href='CarReserveDel.jsp?id=");
      out.print(id);
      out.write("&rday=");
      out.print(bean.getRday());
      out.write("'\">삭제</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t");
 		
			}
	
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</center>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
